services:
  - type: web
    name: es-quant-platform
    env: python
    pythonVersion: "3.12.10"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --timeout 120 --workers 1